// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQRP9OPTzOLJVkmfa6jRMp1jylPCuc6-I',
    appId: '1:399303778108:android:ec904eda5b3e458c4ac839',
    messagingSenderId: '399303778108',
    projectId: 'idreamtest-5e331',
    storageBucket: 'idreamtest-5e331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8SyrwogB375lv2b2KTz199xxwpP2QjII',
    appId: '1:399303778108:ios:4fe20b7a04af07524ac839',
    messagingSenderId: '399303778108',
    projectId: 'idreamtest-5e331',
    storageBucket: 'idreamtest-5e331.appspot.com',
    androidClientId: '399303778108-0t8nnhp98ajhf50calqmccmagq961ovu.apps.googleusercontent.com',
    iosClientId: '399303778108-5os2bo0plo73ooleb3lcn9f9kiaiju90.apps.googleusercontent.com',
    iosBundleId: 'com.example.idreamtest',
  );
}
